---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    app.kubernetes.io/part-of: k8s-event-triage
    app.kubernetes.io/component: event-processor
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    app.kubernetes.io/part-of: k8s-event-triage
    app.kubernetes.io/component: workflow-engine
