apiVersion: v1
kind: Namespace
metadata:
  name: promptfoo-evaluation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promptfoo
  namespace: promptfoo-evaluation
automountServiceAccountToken: false
