registry: ghcr.io
tag: "0.10.1"
imagePullPolicy: IfNotPresent
fullnameOverride: tenant-kagent

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

database:
  postgres:
    bundled:
      enabled: true

rbac:
  namespaces:
    - tenant-kagent-system
    - team-event
    - team-chat

controller:
  replicas: 1
  watchNamespaces:
    - tenant-kagent-system
    - team-event
    - team-chat
  auth:
    mode: trusted-proxy
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "2"
      memory: 512Mi
  substrate:
    enabled: false

substrate:
  enabled: false
substrateWorkerPool:
  create: false

ui:
  replicas: 0
kmcp:
  enabled: false
kagent-tools:
  enabled: false
grafana-mcp:
  enabled: false
k8s-agent:
  enabled: false
kgateway-agent:
  enabled: false
istio-agent:
  enabled: false
promql-agent:
  enabled: false
observability-agent:
  enabled: false
argo-rollouts-agent:
  enabled: false
helm-agent:
  enabled: false
cilium-policy-agent:
  enabled: false
cilium-manager-agent:
  enabled: false
cilium-debug-agent:
  enabled: false
querydoc:
  enabled: false
