apiVersion: v1
kind: ServiceAccount
metadata:
  name: rogue
  namespace: team-rogue
---
apiVersion: v1
kind: Pod
metadata:
  name: rogue-shell
  namespace: team-rogue
  labels:
    app: rogue-shell
spec:
  serviceAccountName: rogue
  automountServiceAccountToken: true
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: curl
      image: curlimages/curl:8.16.0@sha256:463eaf6072688fe96ac64fa623fe73e1dbe25d8ad6c34404a669ad3ce1f104b6
      command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      resources:
        requests:
          cpu: 5m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
