apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: smart-triage-fanout-
  namespace: argo
  labels:
    app.kubernetes.io/part-of: smart-triage-fanout
    platform.com/team: platform
    platform.com/type: demo
spec:
  arguments:
    parameters:
      - name: alert_source
        value: manual
      - name: alert_payload
        value: "{}"
  workflowTemplateRef:
    name: smart-triage-fanout
