#!/bin/bash
# Standalone Holmes → GitLab test script
# Run this to test the integration without Argo Workflows
#
# Defaults match current deployment:
#   Holmes in holmesgpt namespace, health at /healthz
#   GitLab token from K8s Secret or env var

set -e

# Configuration - matches current deployment
HOLMES_URL="${HOLMES_URL:-http://holmes-holmes.holmesgpt.svc.cluster.local:80}"
GITLAB_URL="${GITLAB_URL:-https://gitlab.com}"
GITLAB_PROJECT_ID="${GITLAB_PROJECT_ID:-68265584}"
GITLAB_TOKEN="${GITLAB_TOKEN:-$(kubectl get secret gitlab-token -n argo -o jsonpath='{.data.GITLAB_TOKEN}' 2>/dev/null | base64 -d 2>/dev/null || echo '')}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Test 1: Check Holmes connectivity
test_holmes() {
    log_info "Testing Holmes connectivity at ${HOLMES_URL}..."

    if ! curl -s --connect-timeout 5 "${HOLMES_URL}/healthz" > /dev/null 2>&1; then
        log_warn "Holmes not reachable at ${HOLMES_URL}"
        log_info "Try: kubectl port-forward -n holmesgpt svc/holmes-holmes 5050:80"
        return 1
    fi

    log_info "Holmes is reachable"
    return 0
}

# Test 2: Check GitLab token
test_gitlab_token() {
    log_info "Testing GitLab token..."

    if [ -z "$GITLAB_TOKEN" ]; then
        log_error "GitLab token not found. Set GITLAB_TOKEN env var or ensure gitlab-token secret exists in argo namespace."
        return 1
    fi

    local response
    response=$(curl -s -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        "${GITLAB_URL}/api/v4/user" 2>/dev/null)

    if echo "$response" | grep -q '"username"'; then
        local username
        username=$(echo "$response" | grep -o '"username":"[^"]*"' | cut -d'"' -f4)
        log_info "GitLab token valid (user: ${username})"
        return 0
    else
        log_error "GitLab token invalid"
        return 1
    fi
}

# Test 3: Check GitLab project access
test_gitlab_project() {
    log_info "Testing GitLab project access..."

    local response
    response=$(curl -s -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}" 2>/dev/null)

    if echo "$response" | grep -q '"id":'; then
        local name
        name=$(echo "$response" | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4)
        log_info "Project accessible (${name})"
        return 0
    else
        log_error "Cannot access project ${GITLAB_PROJECT_ID}"
        return 1
    fi
}

# Test 4: Create test issue
test_create_issue() {
    log_info "Creating test GitLab issue..."

    local title="Test Issue $(date +%Y%m%d-%H%M%S) - Holmes Integration"
    local description="## Test Description

This is a test issue created by the Holmes integration test script.

### Test Results
- GitLab token valid
- Project accessible
- Issue creation working

### Timestamp
$(date -u +"%Y-%m-%d %H:%M:%S UTC")

---
*Auto-generated by test-holmes-gitlab.sh*"

    # Escape for JSON
    local json_title
    json_title=$(echo "$title" | sed 's/"/\\"/g')
    local json_desc
    json_desc=$(echo "$description" | sed 's/"/\\"/g' | tr '\n' ' ' | sed 's/  */ /g')

    local response
    response=$(curl -s -X POST \
        -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
        -H "Content-Type: application/json" \
        "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/issues" \
        -d "{\"title\":\"${json_title}\",\"description\":\"${json_desc}\",\"labels\":\"test,holmes-integration\"}" 2>/dev/null)

    if echo "$response" | grep -q '"iid":'; then
        local iid
        iid=$(echo "$response" | grep -o '"iid":[0-9]*' | cut -d: -f2)
        local url
        url=$(echo "$response" | grep -o '"web_url":"[^"]*"' | cut -d'"' -f4)
        log_info "Issue created #${iid}"
        log_info "   URL: ${url}"
        return 0
    else
        log_error "Failed to create issue"
        log_error "Response: ${response}"
        return 1
    fi
}

# Test 5: Full Holmes integration test (if Holmes available)
test_holmes_integration() {
    log_info "Testing full Holmes integration..."

    if ! test_holmes; then
        log_warn "Skipping Holmes integration test - Holmes not available"
        return 0
    fi

    local query="${1:-List all pods in default namespace}"
    local title="${2:-Holmes Investigation Test}"

    log_info "Query: ${query}"

    local response
    response=$(curl -s -X POST "${HOLMES_URL}/api/investigate" \
        -H "Content-Type: application/json" \
        -d "{
            \"source\": \"test-script\",
            \"title\": \"${title}\",
            \"description\": \"${query}\",
            \"subject\": {
                \"kind\": \"Pod\",
                \"name\": \"integration-test\",
                \"namespace\": \"default\"
            },
            \"context\": {
                \"cluster\": \"{{CLUSTER_NAME}}\"
            },
            \"instructions\": \"${query}\",
            \"include_tool_calls\": true,
            \"include_tool_call_results\": false
        }" 2>/dev/null)

    if echo "$response" | grep -q '"analysis"'; then
        log_info "Holmes responded"
        local analysis
        analysis=$(echo "$response" | grep -o '"analysis":"[^"]*"' | head -1 | cut -d'"' -f4)
        log_info "   Analysis preview: ${analysis:0:100}..."
        return 0
    else
        log_warn "Holmes returned unexpected response"
        log_warn "Response: ${response:0:200}"
        return 1
    fi
}

# Main execution
main() {
    echo "========================================"
    echo "Holmes + GitLab Integration Test Suite"
    echo "========================================"
    echo ""

    local failed=0

    # Run tests
    test_gitlab_token || ((failed++))
    test_gitlab_project || ((failed++))
    test_create_issue || ((failed++))
    test_holmes_integration "$@" || true  # Don't count as failure

    echo ""
    echo "========================================"
    if [ $failed -eq 0 ]; then
        log_info "All critical tests passed!"
        exit 0
    else
        log_error "${failed} test(s) failed"
        exit 1
    fi
}

# Run if called directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
