{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stonebranch-uag.serviceAccountName" . }}
  namespace: {{ include "stonebranch-uag.namespace" . }}
  labels:
    {{- include "stonebranch-uag.labels" . | nindent 4 }}
{{- end }}
