apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-webhook-receiver-example
  namespace: kagent-poc
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: receiver-example
data:
  alertmanager.yaml: |
    route:
      receiver: kagent-direct-webhook
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 2m

    receivers:
      - name: kagent-direct-webhook
        webhook_configs:
          - url: http://alertmanager-webhook-eventsource-svc.kagent-poc.svc.cluster.local:12000/alertmanager
            send_resolved: true
