apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: alertmanager-webhook
  namespace: kagent-poc
  labels:
    app.kubernetes.io/name: kagent-event-flow-poc
    app.kubernetes.io/component: webhook-eventsource
spec:
  template:
    nodeSelector:
      kubernetes.io/hostname: k8s-worker1
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    alertmanager:
      endpoint: /alertmanager
      method: POST
      port: "12000"
