apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-eventsource-svc
  namespace: kagent-poc
  labels:
    app.kubernetes.io/name: kagent-event-flow-poc
    app.kubernetes.io/component: webhook-eventsource
spec:
  selector:
    eventsource-name: alertmanager-webhook
  ports:
    - name: http
      port: 12000
      targetPort: 12000
