apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: kagent-poc
  labels:
    app.kubernetes.io/name: kagent-event-flow-poc
    app.kubernetes.io/component: eventbus
spec:
  jetstream:
    version: 2.10.10
    replicas: 1
    streamConfig: |
      maxMsgs: 50000
      maxAge: 168h
      maxBytes: -1
      replicas: 1
      duplicates: 300s
      retention: 0
      discard: 0
