apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  annotations:
    meta.helm.sh/release-name: mcp-memory-server
    meta.helm.sh/release-namespace: kagent
  labels:
    app.kubernetes.io/component: remote-mcp-server
    app.kubernetes.io/instance: mcp-memory-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mcp-memory-server
    app.kubernetes.io/version: 0.2.5
    helm.sh/chart: mcp-memory-server-0.2.5
  name: memory-mcp
  namespace: kagent
spec:
  description: Shared persistent knowledge graph memory
  protocol: STREAMABLE_HTTP
  sseReadTimeout: 5m0s
  terminateOnClose: true
  timeout: 30s
  url: http://mcp-memory-server.kagent.svc.cluster.local:3000/mcp
