apiVersion: 1

policies:
  - orgId: 1
    receiver: argo-direct-webhook
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 30s
    repeat_interval: 5m
    routes:
      # Route 1: always send to Redpanda path, then continue to Route 2
      - receiver: argo-redpanda-webhook
        matchers: []
        continue: true
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 5m
      # Route 2: always send to direct Argo EventSource
      - receiver: argo-direct-webhook
        matchers: []
        continue: false
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 5m
