apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: path-b-alertmanager-webhook
  namespace: argo-events
  labels:
    app.kubernetes.io/name: path-b-alertmanager-webhook
    app.kubernetes.io/part-of: k-agent-observability
spec:
  eventBusName: default
  template:
    serviceAccountName: argo-events-sa
    container:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    alertmanager:
      endpoint: /alertmanager
      method: POST
      port: "12000"
